name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn docs:build
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Semantic Release
        run: yarn release
